name: Deploy
on:
  push:
    branches:
      - main
jobs:
    dev-deploy:
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '10.x'
                registry-url: 'https://npm.pkg.github.com'
            - run: npm install
            - name: Create a release
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
