name: Run unit tests
on: [pull_request, workflow_dispatch]
jobs:
    run_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [ '10', '12' ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node }}
            - run: npm install --production=false
            - run: npm lint
            - run: npm test
